### PR TITLE
feat(Commands): ✨ Add localizations for command names & description

### PR DESCRIPTION
**Pull request by Stefouch**
Basically, adding a "name" and a "description" property in the commands.yml translation file under each command will translate the name and description of the command in Discord.

### PR Type

- [x] This PR is a code change that implements a feature request.
- [ ] This PR fixes an issue.
- [ ] This PR adds a new feature that is not an open feature request.
- [ ] This PR is not a code change (e.g. documentation, README, ...)
### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes (wiki).

### CODE REVIEW

**Comment by Stefouch** [comment]
@mprangenberg I have a question for you about the localization of commands' names & descriptions. I need your feedback.

Do you think the command name should be translated too ?

For example, if I add the following lines in the German commands translation file:
```yaml
# ./src/locales/de/commands.yml
roll:
  name: wurfeln
  description: Wirf ein paar Würfel
  # ...
```

Then, in a german server, you'll be able to:
- Type `/wurfeln` to do the exact same thing as `/roll`
- Type `/roll` and Discord will show you `/wurfeln` as a possible choice

This is a cool feature, but I'm afraid it could lead to confusion. What do you think ?

**Comment by mprangenberg** [comment]
That's really neat. I really like it.
The thing is though, we would need to translate the arguments and their options, too. Otherwise it would be too confusing, as you said. Also, we made the deliberate choice to keep dice in the XdX format earlier.
But i'm still torn, as having commands in your own language can be more user friendly, especially for beginners.

**Comment by Stefouch** [comment]
> The thing is though, we would need to translate the arguments and their options, too.

This is possible.

> Also, we made the deliberate choice to keep dice in the XdX format earlier.

Although most arguments/options ask for an integer, this is not possible to change for commands that parses a string, like the command `/roll generic`

*(Exception for the artifact dice option, actually the code only cares of the number)*

**Comment by mprangenberg** [comment]
Well, if you are up to the task, let's do it, why not?
Although I must confess i don't have much time to help at the moment, except for a bit of translating, as i'm swamped at work.

**Comment by Stefouch** [comment]
@mprangenberg All commands and their options/arguments should be localizable with this PR (tested in French).

There are some Discord API restriction to how you translate the names and the descriptions:
- Command's description must be < 100 characters
- Command's name must be lowercase with no punctuation and < 32 characters

After I have merged this PR, I'll refresh the Git Localize and then the German translation of the commands could start.

**Comment by Stefouch** [comment]
PS: I have added CI Tests that validates the localizations of the commands' names & descriptions.
You can test with `npm run test:locale` in you dev environment.

**Pull request merged**
